apiVersion: v1
kind: Service
metadata:
  name: order
  labels:
    app: order
spec:
  selector:
    app: order
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8081
  type: LoadBalancer

